### PR TITLE
Tidy up license related headers

### PR DESCRIPTION
**Pull request by dcousens**
This code has changed far beyond Paul Johnston's original code, it feels misleading to hint at `Version 2.2-beta` or anything similar.  I think this header is appropriate and hopefully adheres to the LICENSE requirements?

### CODE REVIEW

**Comment by dcousens** [comment]
@calvinmetcalf should be ready to merge straight up

**Review by ljharb — COMMENTED** [review]
What’s the advantage of making this change here? In-file boilerplate is something I’m more likely to remove than update, altho im hesitant to touch it at all when it refers to licensing.

**Comment by dcousens** [comment]
Happy to ignore, I simply thought it was misleading ... 3 years ago.

**Comment by dcousens** [comment]
I _think_ the intent was, with the current code reflecting so little of the original (see https://pajhome.org.uk/crypt/md5/sha256.html to compare with https://github.com/browserify/sha.js/blob/9b74ad04c1bdc28e557a85a30da3720f11fe33ca/sha256.js), it seemed appropriate to not infer that this code is representative of that author.

The code is _derived_, which is important for attribution, but, it's in no way "Version 2.1a" or "Version 2.2-beta".

**Comment by ljharb** [comment]
gotcha. unfortunately since you deleted the fork there's no way to recover this PR :-( but if you think it's important and you wanted to open a new one (with some text more like "adapted from v2.whatever") then we can land that.

**Comment by dcousens** [comment]
I don't think it's important, I only made the mistake of opening the cursed https://github.com/pulls

**Pull request closed without merging**
